import { StyleSheet} from 'react-native';
import { Colors } from 'react-native/Libraries/NewAppScreen';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  rootView: {
    flex: 1,
    padding: 0,
    flexDirection: 'column',
  },
  homeScreenText: {
    fontSize: 20, 
    textAlign: 'left', 
    fontWeight: 200,
    color: '#ffffff',
  },
  backgroundImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundGradientFullscreen: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  textBlack:{
    color: Colors.black,
    fontWeight: 'bold',
    fontSize: 48,
    textAlign: 'center',
  },
  textWhiteBig:{
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 48,
    textAlign: 'center',
  },
  textWhiteSmall: {
    color: Colors.white,
    fontSize: 12,
    textAlign: 'center',
    paddingTop: 4,
  },
  textDiscoverScreenTitle:{
    fontWeight: 'bold',
    fontSize: 32,
    marginTop: 8,
    marginBottom: 8,
  },
  welcomeViewBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: '5%',
  },
  touchableOpacity: {
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: '20%',
    borderRadius: 15,
    textAlign: 'center',
    alignContent: 'center',
  },
  touchableOpacityModal: {
    alignItems: 'center',
    backgroundColor: '#0070f2',
    paddingVertical: 10,
    paddingHorizontal: '20%',
    borderRadius: 5,
    textAlign: 'center',
    alignContent: 'center',
  },
  touchableOpacityViewBox: {
    marginBottom: 50,
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
    maxWidth: 300,
  },
  container: {
    flex: 1,
    paddingLeft: 20,
    paddingRight: 20,
  },
  containerSkeleton: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  containerHelper: {
    borderRadius: 15,
    paddingBottom: 10,
  },
  contentContainer: {
    paddingTop: 25,
    flex: 1,
    alignItems: 'center',
  },
  cardInfo: {
    borderRadius: 15,
    minHeight: 160, 
    justifyContent: 'flex-end',
  },
  cardStyle: {
    height: "100%",
    justifyContent: 'flex-end',
    borderRadius: 15,
  },
  searchView: {
    marginBottom: 5,
    flexDirection: 'row',
    padding: 2,
    paddingLeft: 20,
    alignItems: 'center',
    borderRadius: 15,
    height: 40,
  },
  safeAreaPadding: {
    paddingTop: 30,
    paddingBottom: 10,
  },
  carouselLinearGradient: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "100%",
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 15,
  },
  carouselSourceTextStyle: {
    textAlign: 'left',
    fontSize: 8,
    color: "#888888",
    paddingHorizontal: 20,
    paddingBottom: 10,
    position: 'absolute',
  },
  carouselTitleTextStyle: {
    textAlign: 'left',
    fontSize: 25,
    fontWeight: '500',
    color: "#ffffff",
    paddingHorizontal: 20,
    paddingBottom: 20,
    position: 'absolute',
  },
  categoriesCardsRootView: {
    paddingLeft: 20,
    paddingRight: 20,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  categoriesCardsTouchableOpacity: {
    paddingRight: 5,
    paddingBottom: 5,
  },
  flatListCardImage: {
    flex: 1,
    justifyContent: 'center',
    borderRadius: 15,
  },
  flatListCardLinearGradient: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "100%",
    borderRadius: 14,
  },
  flatListCardArticleText: {
    textAlign: 'left',
    fontSize: 15,
    color: Colors.white,
    paddingHorizontal: 20,
    paddingBottom: 20,
    position: 'absolute',
  },
  flatListCardSourceText: {
    textAlign: 'left',
    fontSize: 8,
    color: "#888888",
    paddingHorizontal: 20,
    paddingBottom: 10,
    position: 'absolute',
  },
  footerView: {
    flex: 1,
    paddingBottom: 10,
  },
  renderItemRootViewPadding: {
    flex:1, 
    padding: 20, 
    paddingTop: 60
  },
  savedScreenView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 45,
  },
  paddingTop5: {
    paddingTop: 5,
  },
  paddingTop40: {
    paddingTop: 40,
  },
  bottomSheetView: {
    marginBottom:30,
    marginHorizontal: 10,
    maxWidth: 400,
  },
});